# Generated by Django 5.2.14 on 2026-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('daily', models.JSONField(default=dict)),
                ('recent', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=220)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('body_format', models.CharField(blank=True, default='plain', max_length=16)),
                ('date', models.CharField(blank=True, default='', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('cover_image', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('display', models.JSONField(blank=True, default=dict)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSettingsRow',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'blog settings',
            },
        ),
        migrations.CreateModel(
            name='ShopLead',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('at', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('delivery', models.CharField(blank=True, default='', max_length=200)),
                ('payment', models.CharField(blank=True, default='', max_length=200)),
                ('subtotal', models.FloatField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('lines', models.JSONField(default=list)),
                ('white_glove', models.BooleanField(blank=True, null=True)),
                ('video_call', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
