# Generated by Django 5.2.16 on 2026-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('slug', models.CharField(max_length=220, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('era', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('description', models.JSONField(blank=True, default=list)),
                ('price', models.FloatField(default=0)),
                ('compare_at_price', models.FloatField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-updated_at', '-created_at']},
        ),
    ]
